### ISSUE TITLE
[BUG] [SERVER/EXTENSION] - Memory error

### ISSUE THREAD

**Issue by lookforkivi** [Static-Flow/BurpSuite-Team-Extension#14]
**Describe the bug**
when my burpsuite client connects to server , the server throws out a memory error

**Screenshots**
![image](https://user-images.githubusercontent.com/46741463/130032705-7a2b82de-80b6-45dc-92ab-317df7de7196.png)

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Burp Version: 2021.8.1
 - JDK Version: tested both in oracle 11.0.12 and 11.0.2
 - Golang Version: tested both in go1.15 and go1.13

**Additional context**
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x76ab3f, 0x16)
    /root/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc010000000, 0x64000000, 0x9fdd78)
    /root/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x9e5960, 0x60182000, 0x0, 0x0)
    /root/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x9e5960, 0x300c1, 0x7fceffffffff)
    /root/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x9e5960, 0x300c1, 0x9fdd88, 0x9dfb28)
    /root/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x9e5960, 0x300c1, 0x400100, 0x9dfb28)
    /root/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
    /root/go/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x9e5960, 0x300c1, 0x10100, 0x2)
    /root/go/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x60180180, 0x7fced24a0001, 0x45663d)
    /root/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
    /root/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x0)
    /root/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
    /root/go/src/runtime/proc.go:1146
goroutine 23 [running]:
runtime.systemstack_switch()
    /root/go/src/runtime/asm_amd64.s:330 fp=0xc0000c99e8 sp=0xc0000c99e0 pc=0x4594a0
runtime.mallocgc(0x60180180, 0x6e6b20, 0x1, 0x0)
    /root/go/src/runtime/malloc.go:1032 +0x895 fp=0xc0000c9a88 sp=0xc0000c99e8 pc=0x40da15
runtime.makechan(0x6e7c40, 0x4010010, 0xc00015c0e0)
    /root/go/src/runtime/chan.go:106 +0x153 fp=0xc0000c9ad0 sp=0xc0000c9a88 pc=0x406523
github.com/Static-Flow/BurpSuiteTeamServer/chatapi.ServeWs(0xc000094140, 0x7daaa0, 0xc00015c0e0, 0xc00016a300)
    /root/go/src/github.com/Static-Flow/BurpSuiteTeamServer/chatapi/BurpClient.go:386 +0x304 fp=0xc0000c9b60 sp=0xc0000c9ad0 pc=0x6afe54
main.main.func2(0x7daaa0, 0xc00015c0e0, 0xc00016a300)
    /root/go/src/github.com/Static-Flow/BurpSuiteTeamServer/cmd/BurpSuiteTeamServer/BurpSuiteTeamServer.go:99 +0x48 fp=0xc0000c9b90 sp=0xc0000c9b60 pc=0x6b67a8
net/http.HandlerFunc.ServeHTTP(0xc000078ca0, 0x7daaa0, 0xc00015c0e0, 0xc00016a300)
    /root/go/src/net/http/server.go:2036 +0x44 fp=0xc0000c9bb8 sp=0xc0000c9b90 pc=0x673354
net/http.(*ServeMux).ServeHTTP(0x9df660, 0x7daaa0, 0xc00015c0e0, 0xc00016a300)
    /root/go/src/net/http/server.go:2416 +0x1bd fp=0xc0000c9c18 sp=0xc0000c9bb8 pc=0x67522d
net/http.serverHandler.ServeHTTP(0xc0000e80e0, 0x7daaa0, 0xc00015c0e0, 0xc00016a300)
    /root/go/src/net/http/server.go:2831 +0xa4 fp=0xc0000c9c48 sp=0xc0000c9c18 pc=0x6761a4
net/http.(*conn).serve(0xc00008aaa0, 0x7db1e0, 0xc00011e200)
    /root/go/src/net/http/server.go:1919 +0x875 fp=0xc0000c9fc8 sp=0xc0000c9c48 pc=0x6721b5
runtime.goexit()
    /root/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000c9fd0 sp=0xc0000c9fc8 pc=0x45b571
created by net/http.(*Server).Serve
    /root/go/src/net/http/server.go:2957 +0x384
goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fced7194010, 0x72, 0x0)
    /root/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000f0018, 0x72, 0x0, 0x0, 0x765c5a)
    /root/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
    /root/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000f0000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /root/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0000f0000, 0xc0000e3978, 0xc0000e3998, 0x42e5b1)
    /root/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000086a00, 0x10666b31a69f8eee, 0xc0000e39a8, 0xc0000e3a08)
    /root/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000086a00, 0x337b4aaa, 0x337b4aaa000e39a8, 0x611e0f03, 0xc0000e3a08)
    /root/go/src/net/tcpsock.go:261 +0x47
crypto/tls.(*listener).Accept(0xc0000874e0, 0xc0000e3a58, 0x18, 0xc000000300, 0x676664)
    /root/go/src/crypto/tls/tls.go:59 +0x37
net/http.(*Server).Serve(0xc0000e80e0, 0x7da720, 0xc0000874e0, 0x0, 0x0)
    /root/go/src/net/http/server.go:2925 +0x280
net/http.(*Server).ServeTLS(0xc0000e80e0, 0x7da820, 0xc000086a00, 0x767b9e, 0xe, 0x767b90, 0xe, 0x0, 0xc0000da230)
    /root/go/src/net/http/server.go:2997 +0x275
net/http.(*Server).ListenAndServeTLS(0xc0000e80e0, 0x767b9e, 0xe, 0x767b90, 0xe, 0x0, 0x0)
    /root/go/src/net/http/server.go:3154 +0x145
main.main()
    /root/go/src/github.com/Static-Flow/BurpSuiteTeamServer/cmd/BurpSuiteTeamServer/BurpSuiteTeamServer.go:121 +0xb05
goroutine 21 [select]:
github.com/Static-Flow/BurpSuiteTeamServer/chatapi.(*Hub).Run(0xc000094140)
    /root/go/src/github.com/Static-Flow/BurpSuiteTeamServer/chatapi/ServerHub.go:129 +0x444
created by main.main
    /root/go/src/github.com/Static-Flow/BurpSuiteTeamServer/cmd/BurpSuiteTeamServer/BurpSuiteTeamServer.go:32 +0x48b

**Comment by Static-Flow** [comment]
Hi,

Thanks for raising this issue. How much memory does the machine running the server have?

**Comment by Static-Flow** [comment]
I believe I have fixed this. You'll need to pull down the update via git to get the new server code. Please re-open if this issue persists.
