### ISSUE TITLE
[FEATURE] EXTENSION  for  burp suite1.7.37

### ISSUE THREAD

**Issue by mohammed-sec2010** [Static-Flow/BurpSuite-Team-Extension#3]
I test your extension and it was amazing, it works only in burpsuite2.1.03 ...could you please add a new extension that works in burp suite 1.7.37? because we are fall in love with burpsuite1.7.37 

![Capture](https://user-images.githubusercontent.com/11797933/64676311-f650c600-d47d-11e9-84d2-c76d8d851b74.PNG)

**Comment by Static-Flow** [comment]
Version 2.0 works in both

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
