### ISSUE TITLE
[FEATURE] [Auto Save Config] - Auto Save/Load the Configuration

### ISSUE THREAD

**Issue by arbazkiraak** [Static-Flow/BurpSuite-Team-Extension#4]
Hello,

* Thanks for building this collaborative extension.

I Believe it is missing an important feature of auto-saving config on close and loading config on startup. 

`https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html#saveConfig()`

Best,
Hussain

**Comment by Static-Flow** [comment]
I have added this feature in 2.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
