### ISSUE TITLE
[BUG] [SERVER/EXTENSION] - TITLE

### ISSUE THREAD

**Issue by mohammed-sec2010** [Static-Flow/BurpSuite-Team-Extension#8]
the BurpSuiteTeamServer worked in kali Linux only and it is not working in the ubuntu subsystem and windows 10 (go1.13.5.windows-amd64), why?
![Capture](https://user-images.githubusercontent.com/11797933/71185331-4c5ab400-228c-11ea-94f8-c8612c8a1ec9.PNG)

**Comment by Static-Flow** [comment]
I believe I have fixed this issue. It seems to be due to a Java to Go TLS bug. Please pull the new server and see if it is fixed.
